# Generated by Django 5.1.7 on 2025-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iska_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='short_description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
