# Generated by Django 5.1.7 on 2025-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iska_app', '0003_post_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='key_words',
            field=models.CharField(max_length=200),
        ),
    ]
